photoalbum/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photo-album/', include('photos.urls', namespace='photoalbum')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photos/urls.py
from django.urls import path
from . import views

app_name= 'photoalbum'

urlpatterns = [
    path("", views.gallery, name='gallery'),
    path("photo/add/", views.addPhoto, name="add"),
    path("photo/<str:pk>/", views.viewPhoto, name="photo"),

]

photos/models.py
from django.db import models



# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class Photo(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(null=False, blank=False)
    description = models.TextField()

    def __str__(self):
        return self.description[:25]

photos/views.py
from django.shortcuts import render, redirect
from .models import Category, Photo

# Create your views here.
def gallery(request):
    cetegory = request.GET.get('category')
    if cetegory == None:
        photos = Photo.objects.all()
    else:
        photos = Photo.objects.filter(category__name=cetegory)

    categories = Category.objects.all()
    context = {
        'categories': categories,
        'photos': photos,
    }
    return render(request, 'photos/gallery.html', context)


def viewPhoto(request, pk):
    photo = Photo.objects.get(id=pk)
    return render(request, 'photos/photo.html',{'photo':photo})


def addPhoto(request):
    categories = Category.objects.all()

    if request.method=='POST':
        data = request.POST
        image=request.FILES.get('image')

        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['new_category'] !='':
            category, created = Category.objects.get_or_create(name=data['new_category'])
        else:
            category = None

        photo = Photo.objects.create(
            category=category,
            description=data['description'],
            image=image,
        )

        return redirect('photoalbum:gallery')

    context = {
        'categories': categories,
    }
    return render(request, 'photos/add.html', context)

photos/templates/photos/add.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Photo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">


</head>
<body class="m-5">
    <div class="container ">
        <div class="row justify-content-center">
            <div class="col-md-6">
            <a href="{% url 'photoalbum:gallery' %}" class="btn btn-dark my-3">Go Back</a>
              <div class="card">
                  <form action="" method="POST" enctype="multipart/form-data">

                      {% csrf_token %}
                      <div class="input-group mb-3">
                          <span class="input-group-text" id="inputGroup-sizing-default">Description</span>
                          <input required type="text" name="description" placeholder="Share your story" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                      </div>

                      <select name= "category" class="form-select" aria-label="Default select example">
                          <option selected value="none">Select the category</option>
                          {% for category in categories%}
                          <option value="{{category.id}}">{{category.name}}</option>
                          {% empty %}
                          <h3>No category available</h3>
                          {% endfor %}
                      </select>

                      <div class="input-group mb-3 pt-3">
                          <span class="input-group-text" id="inputGroup-sizing-default">Crate a new category</span>
                          <input type="text" name="new_category" placeholder="Create a new one" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                      </div>

                      <div class="input-group mb-3 ">
                          <input required type="file" name="image" class="form-control" id="inputGroupFile02">
                          <label class="input-group-text" for="inputGroupFile02">Upload Image</label>
                      </div>

                      <button type="submit" class="btn btn-primary">Submit</button>

                  </form>
              </div>
            </div>
        </div>
    </div>

</body>
</html>

photos/templates/photos/gallery.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gallery</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <style>
        .image-thumbail{
            height: 200px;
            object-fit: cover;

        }
    </style>
</head>
<body class="m-5">
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <div class="card">
                    <div class="card-header">
                        Categories
                    </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <a href="{% url 'photoalbum:gallery'%}">All</a>
                            </li>
                            {% for category in categories %}
                            <li class="list-group-item">
                                <a href="{% url 'photoalbum:gallery' %}?category={{category.name}}">{{category.name}}</a>
                            </li>
                            {% endfor %}


                            <a href="{% url 'photoalbum:add' %}" class="btn btn-dark btn-block btn-sm m-1">Add Photo</a>

                        </ul>
                </div>

            </div>
            <div class="col-md-9">
                <div class="row">
                    {% for photo in photos %}
                    <div class="col-md-4">
                        <div class="card my-2">
                          <img class="image-thumbail" src="{{photo.image.url}}" class="card-img-top" alt="...">

                            <div class="card-body">
                            <small>Category: {{photo.category.name}}</small>
                            </div>
                            <a href="{% url 'photoalbum:photo' photo.pk %}" class="btn btn-outline-dark btn-sm m-1">View</a>

                        </div>
                    </div>
                    {% empty %}
                    <h3>No Photo...</h3>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>

</body>
</html>

photos/templates/photos/photo.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Photo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body class="m-5">
    <div class="container">
        <div class="row justify-container">
            <div class="col">
                <a href="{% url 'photoalbum:gallery' %}" class="btn btn-dark my-3">Go Back</a>
                
                <div style="height:90vh;">
                    <img style="max-width: 100%; max-height:100%;"
                            src="{{photo.image.url}}" alt="">

                    <p class="m-2">{{photo.description}}</p>
                </div>

            </div>
        </div>
    </div>


</body>
</html>